variables:
  PKG_IND: $CI_COMMIT_SHORT_SHA
  PKG_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"

stages:
  - test
  - build
  - publish
  - release

image: fedora:latest

test_lint:
  stage: test
  script:
    - echo "Installing packages"
    - dnf install -y which ruff
    - echo "Running linting check with $(which ruff)"
    - ruff check .

test_types:
  stage: test
  allow_failure: false
  script:
    - echo "Installing packages"
    - dnf install -y python3-pip
    - echo "Generating venv"
    - python -m venv venv
    - source venv/bin/activate
    - pip install basedpyright .
    - echo "Performing type check"
    - 'basedpyright --gitlabcodequality ci-report.json -p ./pyproject.toml
      rdp_fed_admm'
    - echo "Checking type coverage"
    - basedpyright --ignoreexternal --verifytypes rdp_fed_admm
  artifacts:
    reports:
      codequality: ci-report.json

fedora_build:
  stage: build
  script:
    - echo "Installing packages"
    - dnf install -y which hatch
    - echo "Building with $(which hatch)"
    - hatch build
  artifacts:
    paths:
      - "./dist/*.whl"

publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  dependencies:
    - fedora_build
  script:
    - dnf install -y jq
    - ls -l ./dist/*.whl
    - 'export FILE=$(ls ./dist/*.whl)'
    - 'export FNAME=$(basename $FILE)'
    - 'echo FNAME=$FNAME > publish.env && echo $FILE'
    - 'cat publish.env'
    - 'echo $PKG_URL/$FNAME $FILE'
    - 'curl --verbose --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
      --upload-file $FILE "$PKG_URL/$FNAME"'
    - 'curl --verbose --header "PRIVATE-TOKEN: ${CI_API_TOKEN}"
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=${CI_COMMIT_TAG}"'
    - cat release_notes.md
  artifacts:
    paths:
      - release_notes.md
    reports:
      dotenv: publish.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  dependencies:
    - publish
  script:
    - echo "Running release job"
    - echo $FNAME
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: $CI_COMMIT_SHA
    ref: $CI_COMMIT_SHA
    assets:
      links:
        - name: $FNAME
          url: $PKG_URL/$FNAME
