variables:
  PKG_IND: $CI_COMMIT_SHORT_SHA
  PKG_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/1.0.0/p1-573.pdf"

stages:
  - test
  - build

image: fedora:latest

test_lint:
  stage: test
  script:
    - echo "Installing packages"
    - dnf install -y which ruff
    - echo "Running linting check with $(which ruff)"
    - ruff check .

test_types:
  stage: test
  allow_failure: false
  script:
    - echo "Installing packages"
    - dnf install -y python3-pip
    - echo "Generating venv"
    - python -m venv venv
    - source venv/bin/activate
    - pip install basedpyright .
    - echo "Performing type check"
    - 'basedpyright --gitlabcodequality ci-report.json -p ./pyproject.toml
      rdp_fed_admm'
    - echo "Checking type coverage"
    - basedpyright --ignoreexternal --verifytypes rdp_fed_admm
  artifacts:
    reports:
      codequality: ci-report.json

fedora_build:
  stage: build
  script:
    - echo "Installing packages"
    - dnf install -y which hatch
    - echo "Building with $(which hatch)"
    - hatch build
  artifacts:
    paths:
      - "./dist/*.whl"
