[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "rdp-fed-admm"
description = "Rényi Differentially Private Federated ADMM"
version = "1.1.0"
readme = "README.md"
authors = [
  { name="Alex Traios", email="altr@csd.uoc.gr" },
  { name="George Vourvachakis", email="gv@materials.uoc.gr" },
]
requires-python = ">=3.12"
dependencies = [
  "numpy>=1.19.5"
]
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Operating System :: POSIX :: Linux",
]

[project.scripts]
rdp-fed-admm = "rdp_fed_admm.rdp_fed_admm:rdp_fed_admm"

[tool.pyright]
reportConstantRedefinition = false
reportUnsafeMultipleInheritance = false
reportUnusedCallResult = false
reportExplicitAny = false

[tool.ruff.lint.pycodestyle]
max-doc-length = 72
ignore-overlong-task-comments = true

[tool.ruff.lint]
preview = true
ignore = [
  # {upper,lower}case names
  "N803", "N806", "N812", "E741",

  # missing docstrings
  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",

  # minimize blank lines in docstrings
  "D203", "D213",
]
select = [
   'E', 'W', 'D', 'I', 'N', 'C4', 'EXE',
]
